In [49]:
# Simple Arithmatic
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

print("add:",np.add(a,b))
print("sum:",np.sum([a,b]))
print("sum with axis:",np.sum([a,b],axis=1)) #sum each array
print("cumsum a:",np.cumsum(a),"\n")

print("subtract:",np.subtract(a,b))
print("difference:",np.diff(a))
print("difference twice:",np.diff(a,n=2),"\n")

print("multiply:",np.multiply(a,b))
print("prod:",np.prod(a))
print("prod with axis:",np.prod([a,b],axis=1))
print("cumprod",np.cumprod(a))
print("divide:",np.divide(a,b))
print("power:",np.power(a,b),"\n")
print("mod:",np.mod(a,b)) #more commonly used
print("remainder:",np.remainder(a,b))
print("divmod:",np.divmod(b,a)) #b/a --> returns two arrays, quotients, and mod

c=np.array([-1,-5,3])

print("absolute:",np.absolute(c))

add: [ 7  9 11 13 15]
sum: 55
sum with axis: [15 40]
cumsum a: [ 1  3  6 10 15] 

subtract: [-5 -5 -5 -5 -5]
difference: [1 1 1 1]
difference twice: [0 0 0] 

multiply: [ 6 14 24 36 50]
prod: 120
prod with axis: [  120 30240]
cumprod [  1   2   6  24 120]
divide: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
power: [      1     128    6561  262144 9765625] 

mod: [1 2 3 4 5]
remainder: [1 2 3 4 5]
divmod: (array([6, 3, 2, 2, 2]), array([0, 1, 2, 1, 0]))
absolute: [1 5 3]


In [ ]:
# Rounding decimals - Truncation, rounding, floor, ceiling

import numpy as np

a=np.array([2.4364,3.1534,2.5,3.678,-2.26,-2.86,-2.5])

print(np.trunc(a))
print(np.around(a))
print(np.floor(a))
print(np.ceil(a))

[ 2.  3.  2.  3. -2. -2. -2.]
[ 2.  3.  2.  4. -2. -3. -2.]
[ 2.  3.  2.  3. -3. -3. -3.]
[ 3.  4.  3.  4. -2. -2. -2.]


In [ ]:
# Logs

import numpy as np

a=np.arange(1,10)
print(a)
print(np.log2(a))
print(np.log10(a))
print(np.log(a)) #natural log, e

# log at any base
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
1.7005483074552052


In [ ]:
# LCM - Lowest Common Multiple
import numpy as np

a=4
b=3

print(np.lcm(a,b))

12


In [53]:
# LCM on a array
import numpy as np

a=[1,2,3]

print(np.lcm.reduce(a))

6


In [ ]:
import numpy as np

a=np.arange(1,11)

print(np.lcm.reduce(a))

27720
